/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 12.0
    

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.01
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: false

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    light.min_fill_ratio: 0.6
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.8
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz_max: 3.0
      sigma2_q_xyz_min: 1.0
      sigma2_q_yaw_max: 6.0
      sigma2_q_yaw_min: 3.0
      sigma2_q_r: 40.0

      r_xyz_factor: 6e-4
      r_yaw: 8e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0
      tracking_thres: 3
      lost_time_thres: 1.0
      pitch_diff: 0.2
      yaw_diff: -0.4
      spinning_diff: 0.08
